### ISSUE TITLE
import error on jetson nano

### ISSUE THREAD

**Issue by fnoop** [PINTO0309/Tensorflow-bin#12]
**[Required]** Your device (RaspberryPi3, LaptopPC, or other device name):  
Jetson Nano
  
**[Required]** Your device's CPU architecture (armv7l, x86_64, or other architecture name):  
aarch64

**[Required]** Your OS (Raspbian, Ubuntu1604, or other os name):  
Ubuntu 18.04 (Latest jetson nano sd image - JP4.2.1)

**[Required]** Details of the work you did before the problem occurred:  
Installed provided package:
https://github.com/PINTO0309/Tensorflow-bin/blob/master/tensorflow-2.0.0b1-cp37-cp37m-linux_aarch64.whl

**[Required]** Error message:  
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/srv/maverick/software/python/lib/python3.7/site-packages/tensorflow/__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/srv/maverick/software/python/lib/python3.7/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/srv/maverick/software/python/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/srv/maverick/software/python/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/srv/maverick/software/python/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/srv/maverick/software/python/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/srv/maverick/software/python/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/srv/maverick/software/python/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /srv/maverick/software/python/lib/python3.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)
```

**Comment by PINTO0309** [comment]
@fnoop 
Same issue. https://github.com/PINTO0309/Tensorflow-bin/issues/10#issuecomment-514289194
